# Generated by Django 6.1.1 on 2026-10-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_jobmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('internship', 'Internship'), ('contract', 'Contract'), ('remote', 'Remote')], default='full_time', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_range',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]